name: fcash

services:
  build:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HEMTT_VERSION: ${HEMTT_VERSION:-1.21.0}
        HEMTT_SHA256: ${HEMTT_SHA256:-3ace226eac57bf80203ee40b28a67320d4abecba24e0ddb8c5ed1dcfeb1f46f3}
    volumes:
      - type: bind
        source: .
        target: /workspace
        bind:
          selinux: Z
      - type: bind
        source: ./dist
        target: /output
        bind:
          create_host_path: true
          selinux: Z
