name = "Fuhrizen's Cash"
prefix = "fcash"
mainprefix = "x"
author = "Fuhrizen"

[version]
major = 1
minor = 0
patch = 0
git_hash = 0

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
]

[properties]
author = "Fuhrizen"
